# 虚拟路径映射
virtualPathmap: filepreview
# openoffice配置
openoffice:
  host: 49.233.77.204
  port: 8100
# 系统文件存储路径前缀
filepath:
  windows_file_path: F:\lizqIDEA\selfdiscipline\testFiles\
  linux_file_path: /usr/lizq/project/selfdiscipline/files/
server:
  port: 8081
  # address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://49.233.77.204:3306/selfdisciplinetest?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: selfdisciplineTest
    password: selfdisciplineTest
    driver-class-name: com.mysql.jdbc.Driver
    # hikari连接池的配置
    hikari:
      pool-name: self_discipline_jdbcPool
      # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 100
      # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 300000
      # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      # 不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短.
      max-lifetime: 540000
      connection-test-query: SELECT 1
  freemarker:
    suffix: .ftl
    # Comma-separated list of template paths.（以逗号分隔的模板路径列表。）
    template-loader-path: classpath:/static/web/
    # Enable template caching.
    cache: false
    # Template encoding.
    charset: UTF-8
    # 检查模板位置是否存在。
    check-template-location: true
    # Content-Type value.
    content-type: text/html
    # Enable MVC view resolution for this technology.
    enabled: true
    # Set whether all request attributes should be added to the model prior to merging with the template.
    # 设置是否应该在与模板合并之前将所有请求属性添加到模型中
    expose-request-attributes: false
    # Set whether all HttpSession attributes should be added to the model prior to merging with the template.
    # 设置是否在与模板合并之前将所有HttpSession属性添加到模型中
    expose-session-attributes: false
    # Name of the RequestContext attribute for all views.
    # 所有视图的RequestContext属性的名称。
    request-context-attribute: request
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  # 引入其他yml配置文件（多个以逗号隔开）
  profiles:
    active: redis
  # jpa相关配置
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      format: true
      max_fetch_depth: 1
    hibernate:
      ddl-auto: update
# mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
# showsql
logging:
  level:
    com:
      lzq:
        selfdiscipline:
          ta:
            mapper: debug
          business:
            mapper: debug